import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flexDirection: "column",
    zIndex: 2,
    flex: 1,
  },
  header: {
    height: 60,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    backgroundColor: "#279f27",
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  headerTransparent: {
    height: 60,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    backgroundColor: "transparent",
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  footer: {
    height: 80,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  scrollView: {
    backgroundColor: "pink",
    marginHorizontal: 20,
  },
  activityTitle: {
    fontSize: 36,
    color: "white",
    fontWeight: "bold",
  },
  details: {
    zIndex: 1,
    backgroundColor: "#279f27",
    flexDirection: "column",
    justifyContent: "flex-start",
    padding: 20,
  },
  seperator: {
    marginVertical: 10,
    borderBottomColor: "#737373",
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  day: {
    color: "white",
    marginRight: 10,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderWidth: 0.7,
    borderRadius: 5,
    borderColor: "white",
  },
  text: {
    color: "white",
    fontSize: 14,
  },
  helpButton: {
    zIndex: 1,
    marginTop: 50,
    marginBottom: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 12,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#1e90ff",
  },
  bookingButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    paddingVertical: 15,
    borderRadius: 12,
  },
  bottomBookingButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#474747",
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 12,
  },
});

export default styles;
